version = 1

## Install Packages --------------------------------------------------
[install]
go.pkg-path = "go"
ffmpeg.pkg-path = "ffmpeg"
python3.pkg-path = "python3"
"tomberek/vhs".pkg-path = "tomberek/vhs"
"tomberek/vhs".systems = ["x86_64-linux"]
# gum.pkg-path = "gum"
# gum.version = "^0.14.5"


## Environment Variables ---------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"
A="1"
B="2"

[hook]
on-activate = '''
echo Run initialization
'''

## Profile script ----------------------------------------------------
[profile]
common = '''
alias l="ls -alh"
'''

## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
[services]
myservice.command = "python3 -m http.server"

[build]
vhss.description = "test publish"
vhss.version = "0.0.1"
vhss.command = '''
go mod tidy
go build .
mkdir -p $out/bin
mv vhs $out/bin/.
'''
vhs.description = "test publish"
vhs.version = "0.0.1"
vhs.command = '''
go mod tidy
go build .
mkdir -p $out/bin
mv vhs $out/bin/.
'''

