version = 1

[install]
curl.pkg-path = "curl"
dasel.pkg-path = "dasel"

[vars]
A="1"

[hook]
on-activate = '''
echo Run initialization
'''

[profile]
common = '''
alias l="ls -alh"
'''

[build]
eck.description = "will echo things"
eck.version = "0.0.3"
eck.command = '''
mkdir -p $out/bin
cat > $out/bin/eck <<'EOF'
#!/usr/bin/env bash
echo "$@"
echo RANDOM TOOL USED BY THE OPS FOLKS
curl --version
EOF
chmod +x $out/bin/eck
'''

[options]
systems = ["x86_64-linux"]
