version = 1

[install]
curl.pkg-path = "curl"
hello.pkg-path = "hello"
awscli2.pkg-path = "awscli2"

[vars]
A="1"

[hook]
on-activate = '''
echo Run initialization
'''

[profile]
common = '''
alias l="ls -alh"
'''

[build]
eck.description = "will echo things"
eck.version = "0.0.3"
eck.command = '''
mkdir -p $out/bin
cat > $out/bin/eck <<'EOF'
#!/usr/bin/env bash
echo "$@"
echo RANDOM TOOL USED BY THE OPS FOLKS
curl --version
EOF
chmod +x $out/bin/eck
'''

[build.hello]
command = '''
mkdir -p $out/bin
echo "hello world" > $out/bin/hello-go
chmod +x $out/bin/hello-go
'''
runtime-packages = ["hello"]

[options]
systems = ["x86_64-linux"]
